### PR TITLE
Replace time with an atomic counter

### PR DESCRIPTION
**Pull request by serprex**

### CODE REVIEW

**Comment by jonhoo** [comment]
I'm not sure it is necessary for the system to guarantee uniqueness and monotonicity for sequence numbers issued by _different_ dispatchers. Generally, any given dispatch tree should only have one dispatcher that is tasked with assigning sequence numbers, and the others should use the `*forward` methods instead, re-using the sequence numbers. This should probably be added to the documentation.

Lifting that restriction (obviously) obviates the need for atomics. However, I very intentionally chose time over a counter, because it means that, in theory, if the application is terminated and then re-started, old sequence numbers will not be re-used. As you pointed out in #1, we could use `Instant` for this, though I don't know if its guarantees about monotonicity holds across executions. Does it use something like Linux's `CLOCK_MONOTONIC` under the hood? Given the relaxed semantics above, it also doesn't need to be shared as you mentioned in #1.

**Comment by serprex** [comment]
Instant uses CLOCK_MONOTONIC under the hood, but it doesn't expose that information. Instead one has to create a relative point with Instant::now. Whereas std::time exposes a UNIX_EPOCH for SystemTime

It sounds like `time` suits your needs if you're desiring a monotonic clock that persists program resets. Note that time's precise_time_ns is generally based on time since system start, so it won't persist across system resets

As an aside you should use unwrap_or_else instead of unwrap_or with precise_time_ns so that you aren't querying time when an explicit timestamp exists

**Comment by jonhoo** [comment]
Mmm, that's unfortunate about `Instant`. I know about the no-reboot limitation of `precise_time_ns`, and it's sad, but there doesn't seem to be any good replacement (if I could get the absolute time out of `Instant`, that might be it).

Good point about `unwrap_or_else`. I'd be happy to accept a PR for that.

**Comment by serprex** [comment]
If the lifetime of the counter exceeds the lifetime of the program, then it'd seem best to store a counter inside the struct & expose a method of at least initializing the struct with a specified counter. Then persistence across executions becomes the responsibility of the user

**Comment by jonhoo** [comment]
That's a good point, and arguably a better design than relying on time. I'd be happy to merge a PR that moves to a counter, and adds a `startAt` argument (or something similar). Note that the counter still doesn't need to be atomic though.

**Comment by serprex** [comment]
Updated with 2 functions set_sequence & get_sequence. I wasn't sure how to store a struct-bound sequence number that'd be accessible to users throught Dispatcher while existing for DispatchInner

A more implementation-opaque method to global set/get functions would be to move them into Dispatcher. Even if they don't use the &mut self parameter for now

**Comment by jonhoo** [comment]
I think I would make the initial sequence an (ideally optional) argument to the constructor for `Dispatcher`. Adding a mechanism for reading the current sequence number directly is trickier, since the `Dispatcher` doesn't have access to the `DispatcherInner`. However, it might be that such a method isn't really necessary, since clients can observe the timestamps that come out at the end to see what the counter is currently at.

I'd also want to get rid of the atomics. They add unnecessary overhead given that synchronized counters between dispatchers does not need to be supported.

**Comment by jonhoo** [comment]
@serprex: looks good. Would you mind also adding a doc to `new_with_seed`, and maybe mention the behavior of the counter in the docs (no correlation between dispatchers, starts from zero unless seed is given, monotonically increasing)?

**Comment by serprex** [comment]
Took a stab at it; I'm not the best explainer

**Comment by jonhoo** [comment]
Close, though "dispatcher increments its counter & uses that as the sequence number" should not be prefixed with "When a timestamp is not supplied". It increments a counter and (`s/&/and/`) uses that as the sequence number regardless of whether a seed was supplied by the user or not.

**Comment by serprex** [comment]
No, or_else only executes counter += 1 if ts is None

**Comment by jonhoo** [comment]
Ah, I read "when a timestamp is not supplied" as "when a `seed` is not supplied (to this function)". The behavior you are describing there is already written elsewhere (namely that the system will use _either_ user-supplied times, _or_ the system will keep a counter).

**Comment by serprex** [comment]
I'm being confused by your discussing an optional parameter when Rust lacks support for function overloading & default parameters & variadic parameters

**Comment by jonhoo** [comment]
Let me see if I can write it more clearly.

The way the code is written, there are four possible ways to use the library:
- The user created the dispatcher using `new_with_seed`, and uses `.send()` to send values (i.e., does not use `.forward()`. The system will assign each sent item a monotonically increasing timestamp starting at the value provided to `new_with_seed`.
  - The user created the dispatcher using `new`, and uses `.send()` to send values. In this case, the system will **also** assign each sent item a monotonically increasing timestamp, except that the timestamps start at 0.
- The user created the dispatcher using `new_with_seed`, but uses `.forward()`, not `.send()` to send values. Since `forward()` items already have timestamps, the dispatcher counter will **not** be used.
- The user created the dispatcher using `new`, but uses `.forward()`. Result is the same as above.

Elsewhere in the documentation, it is explained that for any given dispatcher, **either** `.forward()` **or** `.send()` should be used. Mixing and matching the two is not supported. Specifically, in the create description where I differentiate between _serializing_ and _forwarding_ mode (admittedly, that text should refer explicitly to `forward` and `send`).

However, you can choose to use either `.forward()` or `.send()` regardless of whether you called `new` or `new_with_seed`. The docstring for `new_with_seed` currently reads:

> When a timestamp is not supplied, the dispatcher increments its counter & uses that as the sequence number. A program may maintain monotonic sequence numbers between executions by tracking those received, storing them on exit, & restoring state with `new_with_seed`.

This, to me, reads as: if you **do** supply a timestamp when creating a dispatcher (i.e., you use `new_with_seed`, not `new`), the dispatcher will **not** keep a counter. This, in turn, implies that you cannot use `.send()` with a dispatcher created with `new_with_seed`, which is obviously not true. Presumably what you _meant_ by the first sentence is that if a timestamp is not supplied _with an update_ (i.e., `.send()` is used), the a counter will be kept. However, this is not clear from the text as it stands, and is doubly confusing given that it is in the docstring for `new_with_seed` specifically.

My suggestion is to make the docstrings for both `new` and `new_with_seed` very similar. That is, **copy** the docstring from `new` to `new_with_seed`, and change the first sentence to read (new part highlighted):

> Creates a new clocked dispatch _whose automatically assigned sequence numbers start at a given value_.

and then add a paragraph saying something like:

> This method is useful for programs that wish to maintain monotonic sequence numbers between multiple executions of the application. Such an application should track received sequence numbers, store the latest one upon exiting, and then use this method to resume the sequence numbers from that point onward upon resuming.

**Comment by jonhoo** [comment]
Looks great! Would you mind also adding a simple test case for this (basically just that the first received update has the timestamp of the counter), and then I'll merge?

**Comment by jonhoo** [comment]
Thanks for all the work @serprex! We got there in the end :+1:

**Pull request merged**
